version: '3.8'
services:
  backend:
    build: ./appointmentBackend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/hospital_appointments
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password

  frontend:
    build: ./appointmentfrontend
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=hospital_appointments
    ports:
      - "3306:3306"